# -*- encoding: utf-8 -*-
require File.expand_path('../lib/rubysl/version', __FILE__)

Gem::Specification.new do |gem|
  gem.authors       = ["Brian Shirai"]
  gem.email         = ["brixen@gmail.com"]
  gem.description   = %q{Ruby 1.8 standard library meta-gem. Install this gem to install the Ruby standard library on compliant Ruby implementations that provide Ruby 1.8 compatibility.}
  gem.summary       = %q{Ruby 1.8 Standard Library meta-gem.}
  gem.homepage      = "http://rubysl.github.com"

  gem.files         = `git ls-files`.split($\)
  gem.executables   = gem.files.grep(%r{^bin/}).map{ |f| File.basename(f) }
  gem.test_files    = gem.files.grep(%r{^(test|spec|features)/})
  gem.name          = "rubysl"
  gem.require_paths = ["lib"]
  gem.version       = RubySL::VERSION

  gem.add_runtime_dependency "rubysl-abbrev",         "~> 1.0"
  gem.add_runtime_dependency "rubysl-base64",         "~> 1.0"
  gem.add_runtime_dependency "rubysl-benchmark",      "~> 1.0"
  gem.add_runtime_dependency "rubysl-big_decimal",    "~> 1.0"
  gem.add_runtime_dependency "rubysl-cgi",            "~> 1.0"
  gem.add_runtime_dependency "rubysl-cgi-session",    "~> 1.0"
  gem.add_runtime_dependency "rubysl-complex",        "~> 1.0"
  gem.add_runtime_dependency "rubysl-csv",            "~> 1.0"
  gem.add_runtime_dependency "rubysl-curses",         "~> 1.0"
  gem.add_runtime_dependency "rubysl-date",           "~> 1.0"
  gem.add_runtime_dependency "rubysl-dbm",            "~> 1.0"
  gem.add_runtime_dependency "rubysl-delegator",      "~> 1.0"
  gem.add_runtime_dependency "rubysl-digest",         "~> 1.0"
  gem.add_runtime_dependency "rubysl-dl",             "~> 1.0"
  gem.add_runtime_dependency "rubysl-druby",          "~> 1.0"
  gem.add_runtime_dependency "rubysl-english",        "~> 1.0"
  gem.add_runtime_dependency "rubysl-enumerator",     "~> 1.0"
  gem.add_runtime_dependency "rubysl-erb",            "~> 1.0"
  gem.add_runtime_dependency "rubysl-etc",            "~> 1.0"
  gem.add_runtime_dependency "rubysl-expect",         "~> 1.0"
  gem.add_runtime_dependency "rubysl-fcntl",          "~> 1.0"
  gem.add_runtime_dependency "rubysl-file_utils",     "~> 1.0"
  gem.add_runtime_dependency "rubysl-find",           "~> 1.0"
  gem.add_runtime_dependency "rubysl-forwardable",    "~> 1.0"
  gem.add_runtime_dependency "rubysl-ftools",         "~> 1.0"
  gem.add_runtime_dependency "rubysl-gdbm",           "~> 1.0"
  gem.add_runtime_dependency "rubysl-generator",      "~> 1.0"
  gem.add_runtime_dependency "rubysl-getopt_long",    "~> 1.0"
  gem.add_runtime_dependency "rubysl-gserver",        "~> 1.0"
  gem.add_runtime_dependency "rubysl-iconv",          "~> 1.0"
  gem.add_runtime_dependency "rubysl-io-wait",        "~> 1.0"
  gem.add_runtime_dependency "rubysl-ipaddr",         "~> 1.0"
  gem.add_runtime_dependency "rubysl-jcode",          "~> 1.0"
  gem.add_runtime_dependency "rubysl-logger",         "~> 1.0"
  gem.add_runtime_dependency "rubysl-mail",           "~> 1.0"
  gem.add_runtime_dependency "rubysl-mathn",          "~> 1.0"
  gem.add_runtime_dependency "rubysl-matrix",         "~> 1.0"
  gem.add_runtime_dependency "rubysl-monitor",        "~> 1.0"
  gem.add_runtime_dependency "rubysl-mutex",          "~> 1.0"
  gem.add_runtime_dependency "rubysl-mutex_m",        "~> 1.0"
  gem.add_runtime_dependency "rubysl-net-ftp",        "~> 1.0"
  gem.add_runtime_dependency "rubysl-net-http",       "~> 1.0"
  gem.add_runtime_dependency "rubysl-net-imap",       "~> 1.0"
  gem.add_runtime_dependency "rubysl-net-pop",        "~> 1.0"
  gem.add_runtime_dependency "rubysl-net-smtp",       "~> 1.0"
  gem.add_runtime_dependency "rubysl-net-telnet",     "~> 1.0"
  gem.add_runtime_dependency "rubysl-nkf",            "~> 1.0"
  gem.add_runtime_dependency "rubysl-observable",     "~> 1.0"
  gem.add_runtime_dependency "rubysl-open-uri",       "~> 1.0"
  gem.add_runtime_dependency "rubysl-open3",          "~> 1.0"
  gem.add_runtime_dependency "rubysl-openssl",        "~> 1.0"
  gem.add_runtime_dependency "rubysl-open_struct",    "~> 1.0"
  gem.add_runtime_dependency "rubysl-option_parser",  "~> 1.0"
  gem.add_runtime_dependency "rubysl-parse_date",     "~> 1.0"
  gem.add_runtime_dependency "rubysl-pathname",       "~> 1.0"
  gem.add_runtime_dependency "rubysl-pp",             "~> 1.0"
  gem.add_runtime_dependency "rubysl-pretty_print",   "~> 1.0"
  gem.add_runtime_dependency "rubysl-profile",        "~> 1.0"
  gem.add_runtime_dependency "rubysl-profiler",       "~> 1.0"
  gem.add_runtime_dependency "rubysl-pstore",         "~> 1.0"
  gem.add_runtime_dependency "rubysl-pty",            "~> 1.0"
  gem.add_runtime_dependency "rubysl-rational",       "~> 1.0"
  gem.add_runtime_dependency "rubysl-readbytes",      "~> 1.0"
  gem.add_runtime_dependency "rubysl-readline",       "~> 1.0"
  gem.add_runtime_dependency "rubysl-resolv",         "~> 1.0"
  gem.add_runtime_dependency "rubysl-rexml",          "~> 1.0"
  gem.add_runtime_dependency "rubysl-rinda",          "~> 1.0"
  gem.add_runtime_dependency "rubysl-rss",            "~> 1.0"
  gem.add_runtime_dependency "rubysl-scanf",          "~> 1.0"
  gem.add_runtime_dependency "rubysl-sdbm",           "~> 1.0"
  gem.add_runtime_dependency "rubysl-set",            "~> 1.0"
  gem.add_runtime_dependency "rubysl-shellwords",     "~> 1.0"
  gem.add_runtime_dependency "rubysl-singleton",      "~> 1.0"
  gem.add_runtime_dependency "rubysl-soap",           "~> 1.0"
  gem.add_runtime_dependency "rubysl-socket",         "~> 1.0"
  gem.add_runtime_dependency "rubysl-string_io",      "~> 1.0"
  gem.add_runtime_dependency "rubysl-string_scanner", "~> 1.0"
  gem.add_runtime_dependency "rubysl-sync",           "~> 1.0"
  gem.add_runtime_dependency "rubysl-syslog",         "~> 1.0"
  gem.add_runtime_dependency "rubysl-tempfile",       "~> 1.0"
  gem.add_runtime_dependency "rubysl-test-unit",      "~> 1.0"
  gem.add_runtime_dependency "rubysl-thread",         "~> 1.0"
  gem.add_runtime_dependency "rubysl-threads_wait",   "~> 1.0"
  gem.add_runtime_dependency "rubysl-time",           "~> 1.0"
  gem.add_runtime_dependency "rubysl-timeout",        "~> 1.0"
  gem.add_runtime_dependency "rubysl-tk",             "~> 1.0"
  gem.add_runtime_dependency "rubysl-tmpdir",         "~> 1.0"
  gem.add_runtime_dependency "rubysl-tracer",         "~> 1.0"
  gem.add_runtime_dependency "rubysl-tsort",          "~> 1.0"
  gem.add_runtime_dependency "rubysl-un",             "~> 1.0"
  gem.add_runtime_dependency "rubysl-uri",            "~> 1.0"
  gem.add_runtime_dependency "rubysl-weak_ref",       "~> 1.0"
  gem.add_runtime_dependency "rubysl-webrick",        "~> 1.0"
  gem.add_runtime_dependency "rubysl-win32api",       "~> 1.0"
  gem.add_runtime_dependency "rubysl-win32ole",       "~> 1.0"
  gem.add_runtime_dependency "rubysl-xmlrpc",         "~> 1.0"
  gem.add_runtime_dependency "rubysl-yaml",           "~> 1.0"
  gem.add_runtime_dependency "rubysl-zlib",           "~> 1.0"
end
